/**
 * Shape of the Opaque `cryptography` wasm-pack module (`init`, `reconstruct_signing_key_wasm`, …).
 *
 * Implementations are generated by Rust; this interface is the stable SDK surface.
 */
export interface StealthWasmModule {
  /**
   * One-time WASM runtime initialization (safe to call once per page/worker).
   */
  init?(): void;

  /**
   * Fast view-tag prefilter: returns `"NoMatch"` or `"PossibleMatch"`.
   */
  check_announcement_view_tag_wasm(
    viewTag: number,
    viewPrivkeyBytes: Uint8Array,
    ephemeralPubkeyBytes: Uint8Array,
  ): string;

  /**
   * Full ownership check for an announcement against view key + spend pubkey + ephemeral key.
   */
  check_announcement_wasm(
    announcementStealthAddress: string,
    viewTag: number,
    viewPrivkeyBytes: Uint8Array,
    spendPubkeyBytes: Uint8Array,
    ephemeralPubkeyBytes: Uint8Array,
  ): boolean;

  /**
   * Derive one-time stealth address and view tag (sender-side helper).
   */
  derive_stealth_address_wasm(
    viewPrivkeyBytes: Uint8Array,
    spendPubkeyBytes: Uint8Array,
    ephemeralPubkeyBytes: Uint8Array,
  ): { stealthAddress: string; viewTag: number };

  /**
   * Encode PSR attestation metadata for `announce` calldata (view tag + attestation id).
   */
  encode_attestation_metadata_wasm(
    viewTag: number,
    attestationId: bigint,
  ): string;

  /**
   * Build a Circom JSON witness from indexed attestations (see Rust docs).
   */
  generate_reputation_witness(
    attestationsJson: string,
    targetTraitId: string,
    stealthPrivkeyBytes: Uint8Array,
    externalNullifier: string,
  ): string;

  /**
   * Reconstruct the 32-byte one-time stealth **private** key for spend / PSR witness input.
   */
  reconstruct_signing_key_wasm(
    masterSpendPrivBytes: Uint8Array,
    masterViewPrivBytes: Uint8Array,
    ephemeralPubkeyBytes: Uint8Array,
  ): Uint8Array;

  /**
   * Scan announcements JSON for attestation markers for this recipient.
   */
  scan_attestations_wasm(
    announcementsJson: string,
    viewPrivkeyBytes: Uint8Array,
    spendPubkeyBytes: Uint8Array,
  ): string;
}

/** Module shape including default `init` export from wasm-bindgen. */
export type StealthWasmEntry = StealthWasmModule & {
  default?: (input?: unknown) => Promise<StealthWasmModule>;
  init?: (input?: unknown) => Promise<StealthWasmModule>;
};
