/**
 * Starknet deployments of the PSR verification stack.
 *
 * The Groth16 verifier is code-generated by Garaga from the production V2
 * verification key (pinned by `circuits/test/fixtures/v2/`); a new trusted
 * setup changes the class hash, not a storage parameter. Sources and the
 * deployment record live in the `starknet` repo README.
 */

/** `SN_SEPOLIA` chain id (short-string encoding). */
export const STARKNET_SEPOLIA_CHAIN_ID = "0x534e5f5345504f4c4941";

export interface StarknetPsrDeployment {
  /** Garaga-generated `Groth16VerifierBN254` (stateless). */
  groth16Verifier: { classHash: string; address: string };
  /** `OpaqueReputationVerifierV2` wrapper (roots, nullifiers, OPQ-006 seam). */
  reputationVerifier: { classHash: string; address: string };
}

export const STARKNET_SEPOLIA_PSR: StarknetPsrDeployment = {
  groth16Verifier: {
    classHash:
      "0x003c72da2c846e3304885e59fb3e0dae07243d482adc29ef3c248d60ad99992d",
    address:
      "0x01f339dfc3a1509bc3ccd1c7ea1a19c07bc0f89ad7378b505b3edc5f5b13b02e",
  },
  reputationVerifier: {
    classHash:
      "0x04361bf98499842b39bd103f4ddc890a0adf56e060a75d98fca8143fc45fb576",
    address:
      "0x079ada2245bd7f7575c4c67c9ea34edc9c420c57de711762b8ffbb8483823af6",
  },
};
