/**
 * Starknet deployments of the PSR verification stack.
 *
 * The Groth16 verifier is code-generated by Garaga from the production V2
 * verification key (pinned by `circuits/test/fixtures/v2/`); a new trusted
 * setup changes the class hash, not a storage parameter. Sources and the
 * deployment record live in the `starknet` repo README.
 */

/** `SN_SEPOLIA` chain id (short-string encoding). */
export const STARKNET_SEPOLIA_CHAIN_ID = "0x534e5f5345504f4c4941";

export interface StarknetPsrDeployment {
  /** Garaga-generated `Groth16VerifierBN254` (stateless). */
  groth16Verifier: { classHash: string; address: string };
  /** `OpaqueReputationVerifierV2` wrapper (roots, nullifiers, OPQ-006 seam). */
  reputationVerifier: { classHash: string; address: string };
}

export const STARKNET_SEPOLIA_PSR: StarknetPsrDeployment = {
  groth16Verifier: {
    classHash:
      "0x003c72da2c846e3304885e59fb3e0dae07243d482adc29ef3c248d60ad99992d",
    address:
      "0x01f339dfc3a1509bc3ccd1c7ea1a19c07bc0f89ad7378b505b3edc5f5b13b02e",
  },
  reputationVerifier: {
    classHash:
      "0x05cf3d48bdceb355244e8cc284834f62c47fe8049d839df78271a08d9ac1f4c5",
    address:
      "0x017a56e5a3963214781320bb1e007b6b72b97041ab8087261253e80233083eb6",
  },
};
